/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dropboxfolder;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateusz
 */
public class Frame extends javax.swing.JFrame {

    private String path = "", APP_KEY="", APP_SECRET="", token="";
    PanelNewDropbox panelNew = new PanelNewDropbox();
    PanelReadDropbox panelRead = new PanelReadDropbox();
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        radieButtonNewDropbox = new javax.swing.JRadioButton();
        radioButtonReadDropbox = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        threadsTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(radieButtonNewDropbox);
        radieButtonNewDropbox.setSelected(true);
        radieButtonNewDropbox.setText("Nowy Dropbox");
        radieButtonNewDropbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radieButtonNewDropboxStateChanged(evt);
            }
        });
        getContentPane().add(radieButtonNewDropbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 108, -1));

        buttonGroup1.add(radioButtonReadDropbox);
        radioButtonReadDropbox.setText("Wybierz zapisany");
        radioButtonReadDropbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioButtonReadDropboxStateChanged(evt);
            }
        });
        getContentPane().add(radioButtonReadDropbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 37, 119, -1));

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(panelNew);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 11, 270, 150));

        jButton1.setText("Ok!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        jLabel2.setText("Ilość Wątków");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 80, 30));

        threadsTextField.setText("10");
        getContentPane().add(threadsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 50, -1));

        jButton2.setText("Wybierz Folder");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radieButtonNewDropboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radieButtonNewDropboxStateChanged
        if(radieButtonNewDropbox.isSelected()){
            jPanel1.removeAll();
            jPanel1.add(panelNew);
            this.revalidate();
            this.repaint();
        }
    }//GEN-LAST:event_radieButtonNewDropboxStateChanged

    private void radioButtonReadDropboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioButtonReadDropboxStateChanged
        // TODO add your handling code here:
        if(radioButtonReadDropbox.isSelected()){
            jPanel1.removeAll();
            panelRead = new PanelReadDropbox();
            jPanel1.add(panelRead);
            this.revalidate();
            this.repaint();
        }
    }//GEN-LAST:event_radioButtonReadDropboxStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DropboxKey dropboxKey = null;
        if(radieButtonNewDropbox.isSelected()){
            APP_KEY = panelNew.getAPP_KEY();
            APP_SECRET = panelNew.getAPP_SECRET();
            token = panelNew.getToken();
            if(!APP_KEY.equals("")&&!APP_SECRET.equals("")&&!token.equals(""))
            dropboxKey = new DropboxKey(APP_KEY,APP_SECRET,token);
            else JOptionPane.showMessageDialog(this,"Musisz wpisac wszystko");
        }
        else{
            dropboxKey = panelRead.getDropbox();
        }
        if(path.equals("")){
            JOptionPane.showMessageDialog(this,"Musisz wybrać folder");
        }
        else{
            int numberOfThreads = Integer.valueOf(threadsTextField.getText());
        try{
        ReadFileFromFolder read = new ReadFileFromFolder(path, dropboxKey, numberOfThreads);
        this.dispose();
        new StatisticsFrame(read).setVisible(true);
        }catch(NullPointerException e){};
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    JFileChooser chooser = new JFileChooser(); 
    chooser.setCurrentDirectory(new java.io.File("."));
    chooser.setDialogTitle("Wybierz folder");
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    chooser.setAcceptAllFileFilterUsed(false);
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
      path = chooser.getSelectedFile().getAbsolutePath();
      }
    else {
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radieButtonNewDropbox;
    private javax.swing.JRadioButton radioButtonReadDropbox;
    private javax.swing.JTextField threadsTextField;
    // End of variables declaration//GEN-END:variables
}
